services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./static/:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - lyrics

  lyrics:
    build: .
    container_name: lyrics
    restart: always
    environment:
      - REDIS_DNS=redis
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    